"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.BrandMark = BrandMark;
const jsx_runtime_1 = require("react/jsx-runtime");
const utils_1 = require("@/lib/utils");
function BrandMark({ size = 64, className, title }) {
    const labelled = Boolean(title);
    return ((0, jsx_runtime_1.jsxs)("svg", { width: size, height: size, viewBox: "0 0 320 320", fill: "none", xmlns: "http://www.w3.org/2000/svg", role: "img", "aria-hidden": labelled ? undefined : true, "aria-label": title, className: (0, utils_1.cn)('flex-shrink-0', className), children: [labelled ? (0, jsx_runtime_1.jsx)("title", { children: title }) : null, (0, jsx_runtime_1.jsx)("circle", { cx: "160", cy: "160", r: "160", fill: "#2C2C2C" }), (0, jsx_runtime_1.jsxs)("g", { stroke: "#FFFFFF", strokeWidth: "22", strokeLinecap: "round", strokeLinejoin: "round", fill: "none", children: [(0, jsx_runtime_1.jsx)("path", { d: "M67 258V117L161 41L253 121" }), (0, jsx_runtime_1.jsx)("path", { d: "M69 259H223" })] }), (0, jsx_runtime_1.jsxs)("g", { opacity: "0.9", fill: "#1A1A1A", children: [(0, jsx_runtime_1.jsx)("text", { x: "97", y: "225", fontFamily: "Impact, Arial Black, sans-serif", fontSize: "126", fontWeight: "900", transform: "skewX(-11)", children: "A" }), (0, jsx_runtime_1.jsx)("text", { x: "176", y: "226", fontFamily: "Impact, Arial Black, sans-serif", fontSize: "128", fontWeight: "900", transform: "skewX(-6)", children: "H" })] }), (0, jsx_runtime_1.jsxs)("g", { fill: "#F47B20", stroke: "#1A1A1A", strokeWidth: "6", paintOrder: "stroke", strokeLinejoin: "round", children: [(0, jsx_runtime_1.jsx)("text", { x: "90", y: "219", fontFamily: "Impact, Arial Black, sans-serif", fontSize: "126", fontWeight: "900", transform: "skewX(-11)", children: "A" }), (0, jsx_runtime_1.jsx)("text", { x: "171", y: "220", fontFamily: "Impact, Arial Black, sans-serif", fontSize: "128", fontWeight: "900", transform: "skewX(-6)", children: "H" })] })] }));
}
//# sourceMappingURL=BrandMark.js.map